package main

import (
	"bufio"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

func safePrepareOutput(output string) error {
	marker := filepath.Join(output, ".unity-doc-agent-corpus")
	if _, err := os.Stat(output); err == nil {
		if _, markerErr := os.Stat(marker); markerErr != nil {
			return fmt.Errorf("refusing to overwrite unmarked output directory: %s", output)
		}
		if err := os.RemoveAll(output); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(output, 0755); err != nil {
		return err
	}
	return os.WriteFile(marker, []byte("generated by unity-doc-corpus\n"), 0644)
}

func transformOne(sourceAbs, outputAbs string, titles map[string]map[string]string, job transformJob, timer *stageTimer) transformResult {
	var raw []byte
	if err := timer.measure("read_html", func() error {
		var err error
		raw, err = os.ReadFile(job.Path)
		return err
	}); err != nil {
		return transformResult{Err: err}
	}
	var parsed parsedPage
	_ = timer.measure("parse_html", func() error {
		parsed = parseHTML(string(raw))
		return nil
	})
	pageID, err := pageIDFor(job.Section, job.Path, sourceAbs)
	if err != nil {
		return transformResult{Err: err}
	}
	title := parsed.Title
	if title == "" {
		title = pageID
	}
	if docTitle := titles[job.Section][pageID]; docTitle != "" {
		title = docTitle
	}
	sourceRel, _ := filepath.Rel(sourceAbs, job.Path)
	rec := record{
		CanonicalURL: parsed.Canonical,
		ContentChars: len(parsed.Body),
		HeadingCount: len(parsed.Headings),
		Headings:     parsed.Headings,
		LinkCount:    len(parsed.Links),
		MDRel:        "text/" + job.Section + "/" + pageID + ".md",
		PageID:       pageID,
		PageKey:      job.Section + "/" + pageID,
		Section:      job.Section,
		SourceBytes:  len(raw),
		SourceRel:    filepath.ToSlash(sourceRel),
		Title:        title,
		UnityVersion: parsed.Version,
		Body:         parsed.Body,
	}
	_ = timer.measure("hash_source", func() error {
		rec.SourceSHA256 = sha256Hex(raw)
		return nil
	})
	md := writeMarkdown(rec, parsed.Links)
	rec.TextBytes = len(md)
	_ = timer.measure("hash_markdown", func() error {
		rec.TextSHA256 = sha256Hex(md)
		return nil
	})
	if err := timer.measure("write_markdown", func() error {
		mdPath := filepath.Join(outputAbs, filepath.FromSlash(rec.MDRel))
		if err := os.MkdirAll(filepath.Dir(mdPath), 0755); err != nil {
			return err
		}
		return os.WriteFile(mdPath, md, 0644)
	}); err != nil {
		return transformResult{Err: err}
	}
	return transformResult{Record: rec}
}

func build(source, output string, workers int) error {
	start := time.Now()
	timer := newStageTimer()
	if workers < 1 {
		workers = defaultWorkers()
	}
	sourceAbs, _ := filepath.Abs(source)
	outputAbs, _ := filepath.Abs(output)
	for _, required := range []string{"Manual", "ScriptReference"} {
		if info, err := os.Stat(filepath.Join(sourceAbs, required)); err != nil || !info.IsDir() {
			return fmt.Errorf("missing required documentation folder: %s", filepath.Join(sourceAbs, required))
		}
	}
	if err := timer.measure("prepare_output", func() error { return safePrepareOutput(outputAbs) }); err != nil {
		return err
	}
	titles := map[string]map[string]string{}
	_ = timer.measure("load_docdata_titles", func() error {
		titles["Manual"] = loadDocdataTitles(sourceAbs, "Manual")
		titles["ScriptReference"] = loadDocdataTitles(sourceAbs, "ScriptReference")
		return nil
	})
	sectionFiles := map[string][]string{}
	if err := timer.measure("discover_html_files", func() error {
		for _, section := range []string{"Manual", "ScriptReference"} {
			files, err := collectHTML(filepath.Join(sourceAbs, section))
			if err != nil {
				return err
			}
			sectionFiles[section] = files
		}
		return nil
	}); err != nil {
		return err
	}
	var db *sql.DB
	fts5 := false
	if err := timer.measure("sqlite_schema", func() error {
		var err error
		db, fts5, err = createSQLite(filepath.Join(outputAbs, "docs.sqlite"))
		return err
	}); err != nil {
		return err
	}
	defer db.Close()
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	pageStmt, err := tx.Prepare("INSERT INTO pages VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
	if err != nil {
		return err
	}
	defer pageStmt.Close()
	var ftsStmt *sql.Stmt
	if fts5 {
		ftsStmt, err = tx.Prepare("INSERT INTO pages_fts(page_key, title, body) VALUES (?, ?, ?)")
		if err != nil {
			return err
		}
		defer ftsStmt.Close()
	}
	pagesFile, err := os.Create(filepath.Join(outputAbs, "pages.jsonl"))
	if err != nil {
		return err
	}
	defer pagesFile.Close()
	pagesWriter := bufio.NewWriter(pagesFile)
	defer pagesWriter.Flush()
	searchFile, err := os.Create(filepath.Join(outputAbs, "search_index.tsv"))
	if err != nil {
		return err
	}
	defer searchFile.Close()
	searchWriter := bufio.NewWriter(searchFile)
	defer searchWriter.Flush()
	searchWriter.WriteString("page_key\tsection\tpage_id\ttitle\tsource_rel\tmd_rel\tcanonical_url\n")
	var jobs []transformJob
	for _, section := range []string{"Manual", "ScriptReference"} {
		for _, path := range sectionFiles[section] {
			jobs = append(jobs, transformJob{Index: len(jobs), Section: section, Path: path})
		}
	}
	results := make([]transformResult, len(jobs))
	jobCh := make(chan transformJob)
	var wg sync.WaitGroup
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobCh {
				results[job.Index] = transformOne(sourceAbs, outputAbs, titles, job, timer)
			}
		}()
	}
	for _, job := range jobs {
		jobCh <- job
	}
	close(jobCh)
	wg.Wait()

	pageCount := 0
	totalSourceBytes := 0
	totalTextBytes := 0
	for _, result := range results {
		if result.Err != nil {
			return result.Err
		}
		rec := result.Record
		if err := timer.measure("write_jsonl_tsv", func() error {
			data, err := json.Marshal(rec)
			if err != nil {
				return err
			}
			pagesWriter.Write(data)
			pagesWriter.WriteByte('\n')
			fmt.Fprintf(searchWriter, "%s\t%s\t%s\t%s\t%s\t%s\t%s\n", rec.PageKey, rec.Section, rec.PageID, strings.ReplaceAll(rec.Title, "\t", " "), rec.SourceRel, rec.MDRel, rec.CanonicalURL)
			return nil
		}); err != nil {
			return err
		}
		if err := timer.measure("sqlite_insert", func() error {
			if _, err := pageStmt.Exec(rec.PageKey, rec.Section, rec.PageID, rec.Title, rec.SourceRel, rec.MDRel, rec.CanonicalURL, rec.SourceSHA256, rec.TextSHA256, rec.SourceBytes, rec.TextBytes); err != nil {
				return err
			}
			if ftsStmt != nil {
				_, err := ftsStmt.Exec(rec.PageKey, rec.Title, rec.Body)
				return err
			}
			return nil
		}); err != nil {
			return err
		}
		pageCount++
		totalSourceBytes += rec.SourceBytes
		totalTextBytes += rec.TextBytes
	}
	if err := timer.measure("sqlite_commit", func() error { return tx.Commit() }); err != nil {
		return err
	}
	manifest := map[string]any{
		"generated_at_utc":        time.Now().UTC().Format(time.RFC3339Nano),
		"source_root":             sourceAbs,
		"output_root":             outputAbs,
		"sections":                []string{"Manual", "ScriptReference"},
		"page_count":              pageCount,
		"source_html_bytes":       totalSourceBytes,
		"derived_markdown_bytes":  totalTextBytes,
		"derived_to_source_ratio": float64(totalTextBytes) / float64(totalSourceBytes),
		"sqlite_fts5":             fts5,
		"worker_count":            workers,
		"files":                   map[string]string{"pages_jsonl": "pages.jsonl", "search_index_tsv": "search_index.tsv", "sqlite": "docs.sqlite", "text_root": "text"},
		"no_data_loss_note":       "Original HTML, static assets, docdata, and uploads are left intact. Derived Markdown strips page chrome for agent lookup and records source paths plus SHA-256 hashes for every transformed HTML page.",
	}
	if err := timer.measure("write_index", func() error {
		return os.WriteFile(filepath.Join(outputAbs, "index.md"), []byte(indexMarkdown(pageCount, totalSourceBytes, totalTextBytes, fts5)), 0644)
	}); err != nil {
		return err
	}
	timingReport := map[string]float64{}
	for key, value := range timer.seconds {
		timingReport[key] = value
	}
	timingReport["total"] = time.Since(start).Seconds()
	manifest["timings"] = timingReport
	manifestBytes, _ := json.MarshalIndent(manifest, "", "  ")
	manifestBytes = append(manifestBytes, '\n')
	if err := timer.measure("write_manifest", func() error {
		return os.WriteFile(filepath.Join(outputAbs, "manifest.json"), manifestBytes, 0644)
	}); err != nil {
		return err
	}
	os.Stdout.Write(manifestBytes)
	return nil
}

func indexMarkdown(pageCount, sourceBytes, textBytes int, fts5 bool) string {
	return fmt.Sprintf(`# Unity Offline Documentation Agent Corpus

This is a derived lookup corpus generated from offline Unity documentation. It is intended for agents, not humans.

## Files

- `+"`text/`"+` - stripped Markdown pages mirroring `+"`Manual/`"+` and `+"`ScriptReference/`"+`.
- `+"`pages.jsonl`"+` - one metadata record per transformed HTML page.
- `+"`search_index.tsv`"+` - compact page lookup table.
- `+"`docs.sqlite`"+` - SQLite metadata plus FTS5 full-text search when available.
- `+"`manifest.json`"+` - generation summary and source/output paths.

## Lookup Order

1. Search `+"`search_index.tsv`"+` for exact API/page names.
2. Search `+"`docs.sqlite`"+` FTS or `+"`text/`"+` for concept queries.
3. Open the specific Markdown page.
4. Verify critical claims against the original HTML path recorded in the page frontmatter.

## Corpus Summary

- Pages: %d
- Source HTML bytes: %d
- Derived Markdown bytes: %d
- Derived/source byte ratio: %.4f
- SQLite FTS5: %t

Original documentation is not modified by this corpus.
`, pageCount, sourceBytes, textBytes, float64(textBytes)/float64(sourceBytes), fts5)
}
